### ISSUE TITLE
adyen change status order prestashop before payment is finisht

### ISSUE THREAD

**Issue by ikkiedikkie** [Adyen/adyen-prestashop#192] opened 2021-05-05 07:21 UTC
Hello Support,

There is a problem in using adyen with prestashop 1.7.7.2

See the order from 1060€ it is open so the order must not change the staus in prestashop
![1](https://user-images.githubusercontent.com/83693470/117108513-9a8a2d80-ad83-11eb-8b61-784bfba934af.png)

But anyway the order is changed
![2](https://user-images.githubusercontent.com/83693470/117108515-9b22c400-ad83-11eb-8a06-350edc6717a4.png)

It may never changed only if there is a payment

But ok the biggest problem is that in prestashop the order is declared as payed!!!!!! And that is False.
![3](https://user-images.githubusercontent.com/83693470/117108516-9b22c400-ad83-11eb-8bc0-ef47af3f86b0.png)
 

This is a wrong workaround from Adyen.

prestashop 1.7.7.2
chome Versie 90.0.4430.93

**Comment by Morerice** [comment] 2021-05-05 13:13
Hi @ikkiedikkie 

Since the issue is linked to an already live merchant and there aren't any technical details provided, could you please contact our [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)? 

Best regards,
Jean
Adyen

**Comment by ikkiedikkie** [comment] 2021-05-10 07:41
> Hi @ikkiedikkie
> 
> Since the issue is linked to an already live merchant and there aren't any technical details provided, could you please contact our [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)?
> 
> Best regards,
> Jean
> Adyen

Hi Jean,

i did and the support team send me back to github.
what more technical details do you need so i can give them.

best regards ikkie

**Comment by Morerice** [comment] 2021-05-10 11:06
> > Hi @ikkiedikkie
> > Since the issue is linked to an already live merchant and there aren't any technical details provided, could you please contact our [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)?
> > Best regards,
> > Jean
> > Adyen
> 
> Hi Jean,
> 
> i did and the support team send me back to github.
> what more technical details do you need so i can give them.
> 
> best regards ikkie

Hi @ikkiedikkie,

Which plugin version are you currently on? Also, could you please provide us with the [adyen](https://docs.adyen.com/plugins/prestashop#finding-the-logs) log files?

Best regards,
Jean
Adyen

**Comment by ikkiedikkie** [comment] 2021-05-10 14:25
[adyen_notification.zip](https://github.com/Adyen/adyen-prestashop/files/6452743/adyen_notification.zip)

v3.4.0 - door Adyen
prestashop 1.7.7.2

regards Odin

**Comment by Morerice** [comment] 2021-05-11 08:11
@ikkiedikkie 

Thanks for providing us with the requested data.
After downloading your file, I have deleted your comment since the file may include sensitive information which ideally, should not be public. We will be looking into your issue.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment] 2021-05-18 12:43
Hi @ikkiedikkie 

Just to keep you updated, we are currently attempting to communicate with PrestaShop to identify what the `total_paid_real` field actually implies. In the meantime, please be assured that the order was not processed and no money was billed from the customer.

Best regards,
Jean
Adyen

**Comment by ikkiedikkie** [comment] 2021-05-18 15:08
Hi Jean,

thanks for the info, other payment providers use total_paid_real as what is beeing payed in the proces, in this case the order was not been payed and the field has to be NULL.

we will wait for the answer.

thanks in advanced
Odin

**Comment by Morerice** [comment] 2021-06-15 14:12
Hi @ikkiedikkie 

Apologies for the late reply, but we just managed to confer with PrestaShop this week. We identified that the issue is occurring because an `OrderPayment` was being created automatically on Order creation, and not when the payment actually went trough.

We have identified a fix and will be working on it in the near future.

Best regards,
Jean
Adyen

**Comment by ikkiedikkie** [comment] 2021-06-17 16:22
Hi Jean,

that is nice to hear,
lett me know when there is a new version for this,

best regards,

Odin

________________________________
Van: Jeantwan Teuma ***@***.***>
Verzonden: dinsdag 15 juni 2021 16:13
Aan: Adyen/adyen-prestashop ***@***.***>
CC: ikkiedikkie ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Adyen/adyen-prestashop] adyen change status order prestashop before payment is finisht (#192)


Hi @ikkiedikkie<https://github.com/ikkiedikkie>

Apologies for the late reply, but we just managed to confer with PrestaShop this week. We identified that the issue is occurring because an OrderPayment was being created automatically on Order creation, and not when the payment actually went trough.

We have identified a fix and will be working on it in the near future.

Best regards,
Jean
Adyen

**Comment by cyattilakiss** [comment] 2021-07-19 14:35
Hi @ikkiedikkie ,

The 3.7.1 release #221 has been published today which includes the fix for the issue you raised.
I will close this issue for now but please feel free to reopen if the issue still persist. (We are also happy to hear back from you if the issue has been fixed as a confirmation!)

Best,
Attila
Adyen

**Closed by cyattilakiss** 2021-07-19 14:35 UTC
