### ISSUE TITLE
[PW-2817] 5 times the same order in the same second 

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#106] opened 2020-07-31 15:42 UTC
Hi team,

**Describe the bug**
Shopper pays at 18h10 : 1845959526403196
3 minutes later, there is a duplication of the same order for 5 transactions, all withing the same second : 
1345959528082613
1645959528081240
1345959528082647
1645959528081281
4745959528083470

As per the log I don't see anything wrong. First I thought about the shopper that 'spam clicked' the pay button but the fact that the 5 duplicates transactions comes 3 minutes after the first one invalidate this theory.
See attached : 
[adyen_notification.log](https://github.com/Adyen/adyen-prestashop/files/5007795/adyen_notification.log)
[error.log](https://github.com/Adyen/adyen-prestashop/files/5007797/error.log)
[info.log](https://github.com/Adyen/adyen-prestashop/files/5007798/info.log)

The merchant, Degriffstock, is using plugin v2.1.5 with prestashop v1.6.1.18.

Thanks.

**Comment by YanP-Adyen** [comment] 2020-08-03 08:19
The issue repeated yesterday, 3 times : 
4735963722527763
1635963722523058
(merchant ref 570698)

4555963780627221
4755963780635917
(merchant ref 570735)

1855963802601082
4755963802619154
(merchant ref 570731)

I tried clicking multiple times on "Pay button" on the pre-prod website, but it always increment the merchant reference which is not the case here.

**Comment by AlexandrosMor** [comment] 2020-08-03 09:03
Hello @YanP-Adyen,

Thank you for posting this issue, We are going to look at it and come back to you as soon as possible.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment] 2020-08-05 13:52
hello @YanP-Adyen ,

Indeed in the logs there are some transactions in the same time. I beleive it is link to #100. 

regards,
Alexandros

**Comment by YanP-Adyen** [comment] 2020-08-05 15:08
Hi @AlexandrosMor 

Thanks for your feedback.
I don't think so, I tried to do this : clicking multiple times on the Pay Button.
Indeed I find multiple transactions, but with an incremented merchant reference each time.

Here the merchant reference is always the same.

Regards,
Yan

**Comment by cyattilakiss** [comment] 2020-08-26 09:47
Hi @YanP-Adyen 

I was finally able to reproduce this issue on 1.6 and it this issue and I believe it also fixed in the #111 since after that fix I am not able to do so anymore.

After the release please let us know if it indeed works for the merchant as well.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-08-31 06:40
Hi @YanP-Adyen 

I was able to reproduce the issue finally and the only trick was just to spam the pay button when the payment is failed. In this case the order number was not bumped because the cart was not converted to an order. This issue is also fixed with the #111 

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-09-01 09:13
Hi @YanP-Adyen

I will close this issue but please feel free to reopen it if you still experience it after upgrading to the latest release.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-09-01 09:13 UTC

**Comment by SammyCOLIN** [comment] 2020-11-10 10:01
Hi @cyattilakiss and @YanP-Adyen 

I have read the log.file of this issue and I have exactly the same problem : 

1 request to /payments with response OK ("Authorised") and juste after, 1 request to /payments with an error ("status":422,"errorCode":"130","message":"Reference Missing","errorType":"validation") ::

![2020-11-10_10h55_08](https://user-images.githubusercontent.com/73232938/98658561-7c4af400-2343-11eb-8475-2c86ff77ee83.png)

When i look in the second request, there are very strange data sent to Adyen (in red) : 

![image](https://user-images.githubusercontent.com/73232938/98658857-cf24ab80-2343-11eb-8f99-2134bfaf829b.png)

We have a problem because the shopper see an error message after his payment "There was an error with the payment method, please choose another one." but in the Adyen interface (and in the notifications) the payment is OK.

**Comment by cyattilakiss** [comment] 2020-11-12 16:31
Hi @SammyCOLIN ,

I assume the 2 requests are coming from the same customer in the same checkout flow. Can you confirm that?
Could you please check if the place order button remains clickable after the button was clicked but the place order process is still in progress? The place order button should have a spinner and should be disabled meanwhile. If it's possible please try it while you have your network tab open so you see if the button click starts any process in the network.
Are you on the version 2.1.6 or on a later one?

Best,
Attila
Adyen
