### ISSUE TITLE
seem override issue on prestashop 1.6.1.23

### ISSUE THREAD

**Issue by themella** [Adyen/adyen-prestashop#77] opened 2020-04-29 14:46 UTC
Good Morning after module installation on my staging server i have an error when i try to execute cron script.
This error look like override problem so you can see error message below :

[27-Apr-2020 10:49:53 Europe/Rome] PHP Fatal error:  Uncaught Error: Class 'AdminAdyenPrestashopCronController' not found in /home/stagekiteworldsh/public_html/classes/controller/Controller.php:134
Stack trace:
#0 /home/stagekiteworldsh/public_html/classes/Dispatcher.php(359): ControllerCore::getController('AdminAdyenPrest...')
#1 /home/stagekiteworldsh/public_html/admin967ikuijp/index.php(58): DispatcherCore->dispatch()
#2 {main}
  thrown in /home/stagekiteworldsh/public_html/classes/controller/Controller.php on line 134

**Comment by cyattilakiss** [comment] 2020-05-01 15:06
Hi @themella ,

Thank you for raising this issue. I was able to reproduce it, indeed it looks like we made a mistake when we performed the plugin name change from `adyen` to `adyenofficial` due to the marketplace submission. We have just release this fix in the release 2.1.1
I will close this issue for now but please feel free to reopen it if you still experience the issue.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-05-01 15:06 UTC
