### ISSUE TITLE
[PW-2859] 2.1.4 version bug in payment method "EPS" / PrestaShop 1.6.1.9

### ISSUE THREAD

**Issue by ersoftwaregmbh** [Adyen/adyen-prestashop#108] opened 2020-08-05 16:57 UTC
Hi,

when using your 2.1.4 module within a PrestaShop 1.6.1.9 live environment (https://er-software.shop), the payment method "EPS" (Austria) displays a dropdown field to select the customer's bank name. When you click to open the list, it opens a (non-existent) html link on the same domain, which results in a 404 error page instead of unfolding the bank list.

The dropdown list is linked with a <a> tag, which could not be the desired behavior. It should unfold the dropdown list instead. <a class="adyen-checkout__dropdown__button waz0IrxZYBVZZIGFHebqH false" tabindex="0" title="Wählen Sie Ihre Bank" aria-haspopup="listbox"><span class="adyen-	checkout__dropdown__button__text">Wählen Sie Ihre Bank</span></a>

You can reproduce this bug if you install the 2.1.4 module in PrestaShop 1.6.1.9 using a merchant account with "EPS" payment method activated.

Please also watch the video of this bug:

https://drive.google.com/file/d/1B-Ux8GVr3VWW90hAHpHcMAidsFEKJQVy/view

I experienced this behavior with MacOS Catalina, Chrome and Safari browsers, as well as with iOS 13.6 and it' Safari browser.

Please fix it as soon as possible, as "EPS" is widely used by our customers and helps to increase the turnover which is processed via Adyen.

Thanks!

Reinhard Keller, CEO
E&R Software GmbH

**Comment by cyattilakiss** [comment] 2020-08-11 15:02
Hi @ersoftwaregmbh ,

Thank you for raising this issue, it looks indeed weird. That payment method should not try to open any page but should only act as a normal dropdown.
Do you have a staging website where we can reproduce this issue?
We are going to investigate it under the ticket number I just added to the issue title.
We are going to get back to you in 2 weeks.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-08-27 10:25
Hi @ersoftwaregmbh ,

I did some investigation but I couldn't reproduce this issue nor on prestashop 1.6 or 1.7.
Since this dropdown is not a simple html input field it's a common practise to use a tags around the elements. Is there any javascript running on your website which may adjust the behaviour of these html tags? Can it happen that maybe the checkout javascript file is not loaded or blocked and that's why the links are working that way?

Do you have a staging website where we can reproduce this issue?
When you reproduce it could you check the console to see if there are any errors in your browser?

Thanks in advance,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-09-14 13:00
Hi @ersoftwaregmbh ,

I will close this ticket now but please feel free to reopen it if you are still experiencing this issue.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-09-14 13:00 UTC
Labels: Waiting for response
