### ISSUE TITLE
[PW-3315] Order status changed by notifications even if the payment method has been changed

### ISSUE THREAD

**Issue by SammyCOLIN** [Adyen/adyen-prestashop#131] opened 2020-10-21 13:05 UTC
**Describe the bug**
When a user changes payment method (Paypal, etc.) after failed attempts with Adyen, the notification system modified the order status anyway (to canceled). The notification system does not check the real payment method.

**To Reproduce**
1. Create an order
2. Try to pay with Adyen
3. Go back to the site and pay with another method (paypal, etc.)
4. Order created with Payement accepted
5. The notification system modify the status to "canceled" (notifications received from the failed payment attempts of step 2)

**Expected behavior**
The payment method should be checked before changing the status.

**Context**

- Adyen module 2.1.7
- Prestashop 1.6.1.20

**Comment by AlexandrosMor** [comment] 2020-10-23 13:52
Hello @SammyCOLIN,

We created an internal issue to investigate it further. 

kind regards 
Alexandros

**Comment by cyattilakiss** [comment] 2020-10-26 17:29
Hi @SammyCOLIN ,

For each payment we send the cart id as merchant reference which is bumped each time the customer clicks the place order button therefore the notification should only close the order which has the same cart id linked.
In the `Steps to reproduce the behavior:` could you please provide us some more information?
1. Create an order **Any adyen payment method?**
1. Try to pay with Adyen **How do you trigger a failed payment?**
1. Go back to the site and pay with another method (paypal, etc.) **How do you go back to the site, cancel or browser back button?**
1. Order created with Payement accepted **Do you see the same merchantReference for both payments in the log/adyen/info.log ?**
1. The notification system modify the status to "canceled" (notifications received from the failed payment attempts of step 2)

Thank you in advance,
Attila
Adyen

**Comment by SammyCOLIN** [comment] 2020-10-27 08:57
> * Create an order **Any adyen payment method?**
> 
Yes. More precisely we create a "cart", the order is created in Prestashop after the payment process.

> * Try to pay with Adyen **How do you trigger a failed payment?**
> 
For example by inserting a wrong code in the 3D secure step.

> * Go back to the site and pay with another method (paypal, etc.) **How do you go back to the site, cancel or browser back button?**
> 
By clicking on the the link "go back to the merchant site" at the end of the 3D secure step.

> * Order created with Payement accepted **Do you see the same merchantReference for both payments in the log/adyen/info.log ?**
> 
There is no several payment on the Adyen side. There is one payment on Adyen, and another payment with Payal or check.
The merchantReference refers to the ID_CART (which refers to the ID_ORDER). When a customer change his payment method (from Adyen to Paypal for example), the ID_CART does not change on Prestashop. So we receive a failed notification from Adyen which refers to a success payment on paypal.


I think the NotificationProcessor should check the payment method when processing notifications to fix the bug.

**Comment by cyattilakiss** [comment] 2020-10-27 09:42
Hi @SammyCOLIN ,

Thank you for the response.
I tried to reproduce it on our end both on 1.6 and 1.7 PrestaShop versions but unfortunately I couldn't.
The first Adyen 3DS cancelled (failed) payment method has a cart_id: x and when the customer returns to the platform the cart is cloned from the failed one with the id of x+1, therefore when the customer finishes the payment with a check payment for example it has a different cart_id linked than the one for the previous Adyen payment attempt.

Even though we were not able to reproduce the issue we can add a check for the notificationProcessor to check at first the payment if it's Adyen or other payment method. I'm still concerned though why the cart_id is not increased for the new payment attempt in your webshop and wondering if you customised anything maybe in the plugin or in the default order creation process of prestashop?

Best,
Attila
Adyen

**Comment by SammyCOLIN** [comment] 2020-10-27 10:30
When I make a "3D secure authentication error", by inserting a wrong code a each of the 3 attempts, I am redirected on our merchant site. But the offer is still "open" on the Adyen side. We do not receive a 'refused' response, handled by the FrontController, by cloning the cart. So the cart is never cloned. 

![2020-10-27_11h20_14](https://user-images.githubusercontent.com/73232938/97289641-bdbda880-1847-11eb-9b52-62bf362c85d5.png)

**Comment by SammyCOLIN** [comment] 2020-10-27 11:15
I think there is 2 scenarios : 

1) We have examples of cloned cart, but it seems that the new cart is not loaded when the customer make a new payment with another payment method. We have two cart in database but the order created after the payment refers to the initial cart (the one use to make the failed adyen payment)

2) No cloned cart like in my previous comment, because we never received a failed response from Adyen (offer still opened on Adyen).

**Comment by cyattilakiss** [comment] 2020-10-27 11:46
Hi @SammyCOLIN ,

I think this is the right direction where the root cause can be found.

After the customer returns to the merchant site from the 3DS1 authentication page the https://github.com/Adyen/adyen-prestashop/blob/3.1.0/controllers/front/Result.php#L66 result controller should be hit and the controller should do a payments/details request (which is logged in the adyen/info.log file). This request finalises the 3DS1 payment and moves the offer to refused or authorised state. Until this request is done the offer remains open. I assume for some reason the code doesn't reach to the line 66 (linked above) and the /payments/details request is not done.

Could you please verify when placing an order with an [Adyen 3DS1 enabled test card](https://docs.adyen.com/development-resources/test-cards/test-card-numbers/#test-3d-secure-authentication) you see the payments/details request and response in the adyen/info.log file? Do you maybe see an error regarding this request in the error.log file?

If the previous request is done correctly could you please verify when placing an order with an Adyen 3DS1 enabled test card before you authenticate yourself on the issuer page if you see the `redirectShopper` paymentResponse in the `adyen_payment_response` database table with the correct id_cart? If it's there we can be sure that the process doesn't fail here: https://github.com/Adyen/adyen-prestashop/blob/3.1.0/controllers/front/Result.php#L60

Maybe it's also a good idea to quickly try the https://github.com/Adyen/adyen-prestashop/releases/tag/3.0.0 or https://github.com/Adyen/adyen-prestashop/releases/tag/3.1.0 releases instead of the version 2.1.7 because we made some big changes regarding the 3DS1 handling in the new major version. Since you can reproduce this issue on your test environment I think it's easy to see if it solves the problem or not.

Please let me know what are your findings.
Attila
Adyen

**Comment by SammyCOLIN** [comment] 2020-10-27 14:24
> Could you please verify when placing an order with an [Adyen 3DS1 enabled test card](https://docs.adyen.com/development-resources/test-cards/test-card-numbers/#test-3d-secure-authentication) you see the payments/details request and response in the adyen/info.log file? Do you maybe see an error regarding this request in the error.log file?

I have tested with these cards and we receive a "refused response" in the info.log file. In the error.log file we see that we are in the "refused" case with the cart cloned : 

error.log 
![image](https://user-images.githubusercontent.com/73232938/97314143-b1494800-1867-11eb-9b2a-d9c5cc479e32.png)

info.log
![image](https://user-images.githubusercontent.com/73232938/97314268-ce7e1680-1867-11eb-9bbc-7f3ad9b386f4.png)

FrontController code executed
![image](https://user-images.githubusercontent.com/73232938/97313966-7d6e2280-1867-11eb-9036-b478f2990c52.png)

But there is a difference with the behaviour of my error cases : with the adyen test card we are not redirected on the 3D secure page, we stay on our merchant site and we have an error in the checkout page : 
![image](https://user-images.githubusercontent.com/73232938/97314870-6aa81d80-1868-11eb-8120-6bd6145ef13b.png)

**Comment by SammyCOLIN** [comment] 2020-10-27 14:40
Note : a new cart has been created but if i retry to pay, the old cart is used, not the cloned one.

**Comment by cyattilakiss** [comment] 2020-10-28 10:25
Hi @SammyCOLIN ,

About this:
> But there is a difference with the behaviour of my error cases : with the adyen test card we are not redirected on the 3D secure page, we stay on our merchant site and we have an error in the checkout page :
Please reach out to our support team because it can be that your merchant account is not correctly configured. Although it won't solve the problem with the cart.

Could you please update your plugin to the latest version and test these scenarios there? I'm not able to reproduce this issue on my end and therefore it's really hard to advise.

Could you maybe share a staging site with our [support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) so we can check the issue in your envionment?

Best,
Attila
Adyen

**Comment by SammyCOLIN** [comment] 2020-10-28 15:02
I think I have understood the problem. When the cart is cloned (after an Adyen payment error), the new cart is set in the context. When the customer go back in the checkout page, the Cart.php class update the customer_token of the cloned cart. So we have two carts with the same customer_token : when the OPC load the cart with getCartIdByToken() function, the first cart is returned and it is the older, the one used to make the Adyen failed payment, and not the cloned one (with a higher id_cart).

**Comment by SammyCOLIN** [comment] 2020-10-28 15:16
If I remove the base cart used in the Adyen failed payment, at the end of the cloning process, in order to keep only one cart, the new one (cloned), it could resolve the problem ? No side effects ?

![image](https://user-images.githubusercontent.com/73232938/97456242-f7baa780-1938-11eb-9a08-6f5ecb3124b5.png)

**Comment by cyattilakiss** [comment] 2020-10-28 16:28
Hi @SammyCOLIN ,

It can be the issue but not sure since I am also testing it with OPC in my dev environment.
I'd suggest to try and remove the old cart and test it if it indeed solves the issue in your environment as well.
In case it solves it please open a pull request so we can incorporate it in the plugin and when you need to update in the future it will be an easier process.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-10-29 14:26
Hi @SammyCOLIN 

Please let me know if it indeed solved the issue for you and if it did we would really appreciate if you would open a PR with the changes.

Best,
Attila
Adyen

**Comment by SammyCOLIN** [comment] 2020-10-29 14:33
I'm testing the solution to remove the base cart or remove just the customer_token of the base cart.

NOTE : we use the **blockcartmultishop** module.

**Comment by cyattilakiss** [comment] 2020-12-04 10:59
Hi @SammyCOLIN  ,

The issue has been fixed in the release 3.2.0
I will close this issue for now but please let us know if you still face this issue or have any further questions.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-12-04 10:59 UTC
