### ISSUE TITLE
Payment Page Empty

### ISSUE THREAD

**Issue by OguzhanLevent** [Adyen/adyen-prestashop#272] opened 2023-12-14 11:48 UTC
**Describe the bug**
I installed the current version, added items to my cart, and proceeded to the checkout page. On the checkout page, I cannot see the payment methods I selected.

**Screenshots**
![image](https://github.com/Adyen/adyen-prestashop/assets/47975183/c5dfa17a-4945-4440-b31a-af3567a61da1)

Prestashop Version: 1.7.8.8

You can find API results bellow.

![image](https://github.com/Adyen/adyen-prestashop/assets/47975183/ce48d0a2-ef5d-4419-8aae-b859c46d8c31)

Everything looks correct in the api answer, payment methods are also selected in the Prestashop back office and the api is connected.

I guess the hook on the payment page is wrong. The theme I use is Vinova Salehub

**Comment by logeecom** [comment] 2023-12-18 10:18
Hello @OguzhanLevent,

Thank you for reaching out to us regarding this issue,

Judging by the screenshots you provided, it appears that you are experiencing difficulties in displaying the Credit Card and ApplePay payment methods during the checkout process.

Did you ensure that there are no payment methods restricted for the destination country you specified during the checkout process?
![Selection_797](https://github.com/Adyen/adyen-prestashop/assets/20204230/e679e4c3-f12b-49ab-b40a-02966f3ff4e8)



Looking forward to your reply.

Kind regards.

**Comment by OguzhanLevent** [comment] 2023-12-18 12:55
Hello,

Yes, we did a test with the target country selected, there was no problem
in previous versions.

We have two different payment methods, these payment methods receive
payments according to the country they belong to, but now all payments will
be received with Adyen, so there will be no restrictions.

Best regards

Logeecom Belgrade ***@***.***>, 18 Ara 2023 Pzt, 13:18
tarihinde şunu yazdı:

**Comment by logeecom** [comment] 2023-12-20 09:01
Hey @OguzhanLevent 

In order to further investigate this issue, our team would need to log into your shop and examine the reported problem since it can not be reproduced in our environment.
Please do not share the credentials of your store directly on GitHub or through email.

Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new or by sending an e-mail to [[support@adyen.com](mailto:support@adyen.com)](mailto:[support@adyen.com](mailto:support@adyen.com)). 
Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.

Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having. Please add the screenshots, plugin version, Prestashop version, steps to reproduce, Adyen and shop logs, or anything else that can help us in our investigation. 

If you have any questions or concerns, please let us know.

Kind regards.

**Comment by OguzhanLevent** [comment] 2023-12-20 09:24
Hello,

It is very difficult to get in touch with support. Please let's schedule an online meeting where we can discuss the issue in detail.

We can get in touch via the support ticket 03250165.

Best regards

**Closed** 2023-12-21 09:56 UTC
