### ISSUE TITLE
[PW-2860] Refund is sent to the shopper when Prestashop creates voucher

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#107] opened 2020-08-05 16:36 UTC
**Describe the bug**
Following this ticket : https://adyen.zendesk.com/agent/tickets/1485371
The merchant wants to create a voucher on Prestashop. However we send a refund to the shopper.

**To Reproduce**
Creating a voucher (or a price reduction) on a command
PSP Example : 1525961957646175

**Expected behavior**
We should not refund the shopper.

**Additional context**
Plugin version 2.0.5
Prestashop version 1.6

**Comment by cyattilakiss** [comment] 2020-08-11 15:06
Hey @YanP-Adyen ,

I've created an internal ticket for this bug. We are going to try to reproduce it and in case we can verify the bug we are going to release a fix for this asap.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-09-01 09:17
Hey @YanP-Adyen ,

I was able to reproduce this issue but unfortunately it turned out (after contacting with a prestashop developer) that in 1.6 there is no way to detect if a voucher was created along with the credit slip. In 1.7.7 prestashop introduces a "fix" for this by adding the "generate credit slip" for the partial refunds as well. Therefore when you do a partial or full refund you are able to select if you want to create a credit slip and based on that checkbox we do the online refund or not.

In case you cannot move from 1.6 I suggest you to use the full refund and do not select the generate credit clip but the generate voucher option. In this case the plugin will not trigger an online refund.

I will close this ticket for now since we cannot create a proper fix for this, but please feel free to reopen it if you have further questions or other suggestions to fix this issue.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-09-01 09:17 UTC
Labels: bug
