### ISSUE TITLE
Inconsistent Display of Express Checkout Options on Safari - Adyen PrestaShop Module 5.2.1

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#277] opened 2024-11-08 07:16 UTC
**Description:**
I am experiencing an issue with the Adyen payment module on PrestaShop 5.2.1, specifically with the express checkout feature for ApplePay, GooglePay, and PayPal.

**Steps to Reproduce:**
	1.	Install the latest version of the Adyen module for PrestaShop 5.2.1.
	2.	Enable express checkout for ApplePay, GooglePay, and PayPal.
	3.	Open the cart page on Safari with products.

**Expected Behavior:**
All three express checkout buttons (ApplePay, GooglePay, and PayPal) should appear consistently on the cart page.

**Actual Behavior:**
The display of express checkout options is inconsistent. Sometimes all three buttons appear, sometimes only two or one, and sometimes none at all. The issue occurs randomly and is more noticeable in Safari.

**Attachments:**
I’ve included screenshots demonstrating the issue.
![Capture d’écran 2024-11-08 à 08 12 56](https://github.com/user-attachments/assets/4031e30d-cb20-4d8f-98da-95dc36fb03be)
![Capture d’écran 2024-11-08 à 08 13 09](https://github.com/user-attachments/assets/2490d8a4-076f-4f7d-93a2-e71986cf512a)
![Capture d’écran 2024-11-08 à 08 13 18](https://github.com/user-attachments/assets/ed80f0e4-dd12-4288-bebe-9a4c5fc7b4b9)
![Capture d’écran 2024-11-08 à 08 13 33](https://github.com/user-attachments/assets/1e043bc6-e324-403b-a025-af8981637cc0)

**Environment:**
	•	Adyen module version: 5.2.1
	•	Browser: Safari

Please let me know if any additional information is needed.

Feel free to add any additional details or screenshots as needed!

**Comment by adyen-integrations-support** [comment] 2024-11-14 15:23
Hi @alexandrebrubeyonds ,

We have successfully reproduced the issue you reported, and our team is actively working on resolving it. We’ll keep you updated on our progress and let you know once we have a solution in place.

Thank you for your patience.

Best regards

**Comment by adyen-integrations-support** [comment] 2024-11-21 15:43
Hi @alexandrebrubeyonds ,

We wanted to inform you that we are still actively working on resolving the issue. As soon as we have more information or updates to share, we will let you know right away.

Thank you for your patience and understanding while we work on this.

Best regards

**Comment by adyen-integrations-support** [comment] 2024-11-26 12:42
Hi,

Thank you for your patience while we investigated the issue. After further testing, we are currently unable to consistently reproduce the behavior you described, even though we have not yet applied a fix. Can you please test now if the issue still persists? 

If you still have the issue please continue with the next steps:

In order to further investigate this issue, our team would need to log into your shop and examine the reported problem since it can not be reproduced in our environment.
Please do not share the credentials of your store directly on GitHub or through email.
Please, submit your query through our regular support channels by going to this [link](https://authn-live.adyen.com/authn/ui/login?request=eyJBdXRoblJlcXVlc3QiOnsiYWN0aXZpdHlHcm91cCI6IkJPX0NBIiwiY3JlZHNSZWFzb24iOlsiTG9nZ2luZyBpbiB0byBhcHBsaWNhdGlvbiBjYSJdLCJmb3JjZU5ld1Nlc3Npb24iOiJmYWxzZSIsImZvcmdvdFBhc3N3b3JkVXJsIjoiaHR0cHM6XC9cL2NhLWxpdmUuYWR5ZW4uY29tXC9jYVwvbG9iYnlcL3Bhc3N3b3JkLXJlc2V0XC9mb3Jnb3QtcGFzc3dvcmQiLCJyZXF1ZXN0VGltZSI6IjIwMjQtMTEtMjZUMTM6NDE6NDcrMDE6MDAiLCJyZXF1ZXN0ZWRDcmVkZW50aWFscyI6W3siUmVxdWVzdGVkQ3JlZGVudGlhbCI6eyJhY2NlcHRlZEFjdGl2aXR5IjpbeyJBY2NlcHRlZEFjdGl2aXR5Ijp7ImFjdGl2aXR5R3JvdXAiOiJCT19DQSIsImFjdGl2aXR5VHlwZSI6IklNUExJQ0lUIiwibWlsbGlzZWNvbmRzQWdvIjo5MDAwMDB9fV0sInR5cGUiOiJQQVNTV09SRCJ9fSx7IlJlcXVlc3RlZENyZWRlbnRpYWwiOnsiYWNjZXB0ZWRBY3Rpdml0eSI6W3siQWNjZXB0ZWRBY3Rpdml0eSI6eyJhY3Rpdml0eUdyb3VwIjoiQk9fQ0EiLCJhY3Rpdml0eVR5cGUiOiJHUkFDRV9DT09LSUUiLCJtaWxsaXNlY29uZHNBZ28iOjB9fV0sInR5cGUiOiJUV09fRkFDVE9SIn19XSwicmVxdWVzdGluZ0FwcCI6ImNhIiwicmV0dXJuVXJsIjoiaHR0cHM6XC9cL2NhLWxpdmUuYWR5ZW4uY29tXC9jYVwvY2FcL2NvbnRhY3RVc1wvc3VwcG9ydC5zaHRtbCIsInNpZ25hdHVyZSI6IlYwMDNTMDBkTVhUSWNkd0Z3XC80VXd4R2JZNjliVjlMMnpJRjZuXC9yXC8yTUwxdTJuST0ifX0%3D)
  or by sending an e-mail to [[support@adyen.com](mailto:support@adyen.com)](mailto:[support@adyen.com](mailto:support@adyen.com)).

Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.
Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having. Please add the screenshots, plugin version, Prestashop version, steps to reproduce, Adyen and shop logs, or anything else that can help us in our investigation.

If you have any questions or concerns, please let us know.

Kind regards

**Closed** 2024-11-26 12:43 UTC
