### ISSUE TITLE
[PW-3952] Bank amount different of prestashop total paid amount

### ISSUE THREAD

**Issue by didpoule** [Adyen/adyen-prestashop#151] opened 2021-01-27 15:26 UTC
Prestashop version: 1.7.6.9
Adyen version:  3.2.1

Issue:
All along checkout process, total amount is right (in this example : 148.50€).
The request sent to adyen is wrong (see attached log) : 159.50€
Prestashop save the right amount (148.50€) in database after Adyen response in orders table.

The problem occures on (apparently) random orders, independently of cart_rules applied, customers or products.

I didn't succeed to reproduce the bug, every time i log the order total amount in AdyenOfficialPaymentModuleFrontController::buildPaymentData method its correct.

We really need to fix that bug cause customers are billed a higher amount than they should be.
[adyen_example.json.log](https://github.com/Adyen/adyen-prestashop/files/5881198/adyen_example.json.log)

  
![image](https://user-images.githubusercontent.com/24778034/106011160-7b13a280-60ba-11eb-9f26-6a054f93fb9f.png)

**Comment by cyattilakiss** [comment] 2021-01-28 10:15
Hi @didpoule ,

Thank you for raising the issue, I've looked into it briefly and have a couple of questions that we need to continue the investigation.

I see there are 11 items in the basket, each of them with the amount of eur 14,50 (13,68 + 0,82 tax)
That sums to: 159,5 but I see that the Products total is 174 on your screenshot. Is there anything I am missing from the product list?

Then I see in the request that there is 1 piece of discount: "4 recettes / 2 personnes" for eur -8,5 but on the screenshot I see this 3 times.

If I deduct the 3x8,5 from the 174 I get the correct 148,5 but I don't see how to reach to the 174 at the moment.

In case you create a test order with exactly the same items and discounts are you able to reproduce the issue?

I will try to reproduce this issue as soon as I get the answer for the above, I think it should be really clear one: 11 products and 3 discounts right?
------

When we send the amount in the payment request we use a function from prestashop core to get the final total value instead of calculating the total value from the list of the products in the cart here: https://github.com/Adyen/adyen-prestashop/blob/1b4f962cb561f5cbb4ff7ae4f7789e1bdde0b0c3/controllers/front/Payment.php#L220 
With this approach we can be sure that the final total is always the same like in prestashop. (looks like not in this case though)

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2021-01-28 10:30
@didpoule 

sorry 1 more question popped to my mind. How can you add the same discount 3 times to the same cart?

**Comment by didpoule** [comment] 2021-01-28 10:56
@cyattilakiss 
Actually, the cart contains 12 items (see capture below)

So the total products is 14.5 * 12 = 174.
We have a first issue on the product list send then.

I tried to reproduce exactly the same basket in local and the bug does not occures.


Also, i dumped the result  of Cart::getOrderTotal at this position many times on test environnement, i never hard a incorrect value.
adyen-prestashop/controllers/front/Payment.php

For the last question,
We have an override which able to add some rules many times. Theses rules are setted automaticaly.




![image](https://user-images.githubusercontent.com/24778034/106126378-95528c80-615d-11eb-95d3-6186fcfbb9e1.png)

**Comment by cyattilakiss** [comment] 2021-01-28 12:12
@didpoule 

Thank you for the response.
It seems really weird that the cart object at the moment of submitting the order contains only 11 products 🤔 In the request we send only 11 products that we fetch with a default prestashop function: https://github.com/Adyen/adyen-prestashop/blob/1b4f962cb561f5cbb4ff7ae4f7789e1bdde0b0c3/controllers/front/Payment.php#L397 which then makes sense that the cart total is retrieved with 159,5 and not 174 at that certain moment. Beside the discount override what other parts are customised in the prestashop instance you have? Is there any added feature that targets the cart object?

"We have an override which able to add some rules many times" -> do they appear as separate discounts in the https://github.com/Adyen/adyen-prestashop/blob/1b4f962cb561f5cbb4ff7ae4f7789e1bdde0b0c3/controllers/front/Payment.php#L423 discounts array or 1 discount withe a field that indicates that it has been applied 3 times. We only support the default behaviour so each discount that has been applied separately can be applied only once.

Best,
Attila
Adyen

**Comment by didpoule** [comment] 2021-01-28 12:44
@cyattilakiss

We have a layer which aggregate cart_products under a common id from a a different table.
Cart::getProducts() method have been overrided to add this line (907): 
![image](https://user-images.githubusercontent.com/24778034/106139710-0dc14980-616e-11eb-8c79-b34fead85217.png)

This has been added because at the beginning, the basket sent to Adyen was containing each line 2 times. Then this line clear the products before foreach the database request treatment on fullInfos.

"do they appear as separate discounts in the" => Each single rule is added one time, the cart_cart_rule table has been overrided to add a quantity field which is used in treatments.
I see, we have a quantity attribute in Adyen request. We should hydrate it with the right value. I'm not sure it fixes the issue ?
![image](https://user-images.githubusercontent.com/24778034/106140210-bff91100-616e-11eb-9147-7d69994fbed2.png)

**Comment by cyattilakiss** [comment] 2021-01-29 09:18
Hi @didpoule ,

Thank you for the response.
I understand that the Cart::getProducts() has been modified a bit. That should not cause though the getOrderTotal to return a different total than what the cart actually has. We don't calculate the total from the products in the basket since it would probably lead to calculation issues so we always stick to the default platform functions in our plugins.

For the discount quantity you can include your quantity indeed just to send us the correct number of the discounts. It won't solve the getOrderTotal issue though.

What we can and will do is the following to help out with this issue:
 - We are going to add preventive and defensive logic so if we see that the order amount or currency doesn't match at any point in the payment and the cart then we will stop the payment process or if the payment is already done then we are going to flag the order with a new status to let the merchant know that the order needs attention and a payment has been done already.
  - We are also going to add an extra check for processing the notifications to double check if there is any mismatch with the orderTotal or the currency at that point and then it can flag the order with a new status the same way as above.
  
With this extra logic we can prevent this from happening or if it happens after the order is created then we can still flag the order regardless any customisation in the platform.

We are refining the tickets today and going to pick them up next week to release it asap.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2021-02-05 13:28
Hi @didpoule ,

We have create a PR to validate the cart each step when we handle payments and orders so if anything happens to the cart object initiated by any other module or customisation then we are not going to finalize the payment or we are going to tag the order as "needs attention" so the merchants can double check what went wrong. We are also adding quite some extra logging so developers can get a better understanding if such thing happens.

We are going to add an additional extra check to the notification handling as well and some extra visible message to the admin so not just developers can see the details of the issue.

We are going to merge it soon and release the changes next week.

Best,
Attila
Adyen

**Comment by didpoule** [comment] 2021-02-08 08:50
Hi @cyattilakiss 
For my part, I found an issue in our development and fixed it. 
Thank you for your feedback. This update will be usefull for the merchant and for developpers too !

Can i be noticed when this update will be released please ?

Have a nice day,
Jordan.

**Comment by cyattilakiss** [comment] 2021-02-08 08:55
Hi @didpoule ,

Thank you for the update!
I hope so indeed it will be useful.

Of course, this issue will be tagged in the release notes and that will send a notification at the moment we release it.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2021-02-18 12:26
Hi @didpoule ,

The extra verification has been released please let us know if you have any feedback regarding that.
I will close this issue for now but feel free to reopen it in case you have any extra related comments.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2021-02-18 12:26 UTC
