### ISSUE TITLE
Case mismatch between loaded and declared class names: "Adyen\PrestaShop\model\Hashing" vs "Adyen\PrestaShop\Model\Hashing".

### ISSUE THREAD

**Issue by rava3000** [Adyen/adyen-prestashop#136] opened 2020-11-10 19:44 UTC
Hi,

Prestashop 1.7
After installing and configuring the module, I'm getting this error when the DEBUG mode is turned ON :
(1/1) RuntimeException    Case mismatch between loaded and    declared class names: "Adyen\PrestaShop\model\Hashing" vs    "Adyen\PrestaShop\Model\Hashing".
--
in DebugClassLoader.php line   190
at DebugClassLoader->checkClass('Adyen\\PrestaShop\\model\\Hashing',   '/home/samsaru/www/modules/adyenofficial/vendor/composer/../..//model/Hashing.php')in DebugClassLoader.php line 166
at DebugClassLoader->loadClass('Adyen\\PrestaShop\\model\\Hashing')
at spl_autoload_call('Adyen\\PrestaShop\\model\\Hashing')
at ReflectionClass->__construct('Adyen\\PrestaShop\\model\\Hashing')in Container.php line 100
at Container->makeInstanceFromClassName('Adyen\\PrestaShop\\model\\Hashing', array('Adyen\PrestaShop\model\Hashing'   => true))in Container.php line 164
at Container->doMake('Adyen\\PrestaShop\\model\\Hashing', array('Adyen\PrestaShop\model\Hashing'   => true))in Container.php line 177
at Container->make('Adyen\\PrestaShop\\model\\Hashing')in ServiceLocator.php line 65
at ServiceLocator::get('Adyen\\PrestaShop\\model\\Hashing')in ServiceLocator.php line 41
at ServiceLocator::get('Adyen\\PrestaShop\\model\\Hashing')in adyenofficial.php line 122
at AdyenOfficial->__construct()
at ReflectionClass->newInstance()in Container.php line 131
at Container->makeInstanceFromClassName('adyenofficial', array('adyenofficial'   => true))in Container.php line 164
at Container->doMake('adyenofficial', array('adyenofficial'   => true))in Container.php line 177
at Container->make('adyenofficial')in ServiceLocator.php line 65
at ServiceLocator::get('adyenofficial')in Module.php line 1141
at ModuleCore::coreLoadModule('adyenofficial')in Module.php line 1120
at ModuleCore::getInstanceByName('adyenofficial')in Hook.php line 884
at HookCore::exec('actionFrontControllerSetMedia', array('cookie'   => object(Cookie), 'cart' => object(Cart),   'altern' => 2))in FrontController.php line 928
at FrontControllerCore->setMedia()in Controller.php line 277
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 28

Could anyone help me with this problem?

Thanks.

**Comment by cyattilakiss** [comment] 2020-11-11 12:23
Hi @rava3000 ,

Thank you for raising this issue.
I can't reproduce this issue on my end but I believe it's because my server settings are different than yours.
I see that the namespace and the folder structure differs `model` vs `Model`,  we are going to release a fix for it in the next patch. I will tag this issue when the fix is created and when it's released as well.

Best,
Attila
Adyen

**Closed** 2020-11-13 08:11 UTC

**Comment by cyattilakiss** [comment] 2020-12-04 10:58
Hi @rava3000 ,

The issue has been fixed in the release 3.2.0
Please let us know if you still face this issue or have any further questions.

Best,
Attila
Adyen
